krakenjs/zoid

src/component/component.js, src/component/parent.js, src/lib/dom.js, test/component.js, test/test.js
You can test this feature by commenting out dimensions property for xcomponent.create in checkout-components.
Logic??
1. Add a flag of 0 for both width and height if dimensions property not specified in checkout.js.
2. Check if options.dimensions == object? If not, give it (width, height) a number 0.
3. In dom.js changed the popup function: check if with,height==0. If yes, do window,open without passing any size for the window so as to have a new tab open.
=> Feature: Support fill page component (no dimensions)

src/component/parent/index.js
The auto resize does not always work the best especially when shrinking/growing width of the browser. We would however like to tell the iframe to resize itself in certain scenarios without having to have this autoResize functionally.
=> Update index.js to allow resizing when not using autoresize

src/component/component/index.js, test/tests/error.js, test/tests/happy.js
Fix for issue #131.
`getRenderContext()` seemed to be used inconsistently. If an element reference, or any value, was passed, `CONTEXT_TYPE.IFRAME` was validated, regardless of whether the component definition specified a context.
It looks like a work around was put in place for `Component` functions like `renderIframe` and `renderPopup`, where `validateRenderContext(context)` was called directly, and the `CONTEXT_TYPE` was hard-coded to the `ParentComponent` constructor arguments. I refactored these functions to be more consistent, so validation is handled correctly by `getRenderContext(context)`
=> use context as getRenderContext argument

docs/api.md
The API docs do a good job of explaining how to use map-syntax for the url. However, they don't mention how to override the `defaultEnv`. Without that information the user is left having to change the `defaultEnv` variable every time they want to change the environment. I added some notes based on @bluepnume's suggestion in #142.
=> Enhance `url` description

docs/api.md
The docs doesn't explain how to override the `element` property on the `autoResize` section.
=> Improve autoResize description with element property

README.md
Trying to implement this, it took me a while to figure out that I needed to define `MyLoginComponent` on both pages. This isn't stated explicitly in the quick start.
This PR makes it clearer and easier to copy paste for a working example.
=> Make instructions for quick start example more explicit

index.js
Solves: https://github.com/krakenjs/xcomponent/issues/152
When included by webpack you can choose if you want to include with or without bridge support the same way react does it (https://github.com/facebook/react/blob/master/packages/react/npm/index.js):
```
plugins: [
new webpack.DefinePlugin({
'process.env': {
'NODE_ENV': JSON.stringify(process.env.NODE_ENV),
'XCOMPONENT_EXCLUDE_IE_BRIDGE': true
}
})
]
```
=> Make it optional to include IE bridge support when importing as module

docs/example.md
Create does validation on the dimensions object to make sure the values entered are a px or % string, if they are not an error is thrown
=> (fix) dimesions needs to be px or %

src/component/component/validate.js, src/component/parent/index.js
This fixes two typos found in validation and parent error messages.
=> Fix validation and parent error messages typos

src/component/parent/props.js
escaping every query param value instead of in xcomponent clients.
=> Fix: query values should be escaped

src/component/component/index.js, src/component/parent/index.js, test/component.jsx, test/tests/error.js
Again for the `zoid-v6` branch
=> feat(validate-call-onerror-zoidv6): Calling  prop, if it exists, if prop validation throws an error

docs/example.md
This updates the React example snippet to match the example on `docs/api.md`. I don't believe that Zoid has a `react` property on the Component instance anymore, so this updates it to use `Component.driver` and specifies react as the framework.
=> Update React example to use Component.driver syntax

src/component/component.js
Just got this error on our app, I wanted to fix the typo 👍 
Thanks for open sourcing
=> Fix Typo in Error: `zoid desroyed all`

docs/api.md
Issue 241: Updated the documentation around containerTemplate and prerenderTemplate to include information on events.  Also clarified that the opts parameter is the same for both functions, and included a link to view the default containerTemplate.
=> #241 Update API doc with event info for templates

src/component/validate.js, test/tests/validation.js
Is there a specific reason to enforce a dash in the tag name? I stumbled upon this one while upgrading from zoid v6 (where dashless tag names were still working) to v9 and it came pretty unexpected.
I've added a test-case to cover my change however I'm not sure whether the place where I put it is right because it's the first test in that file that doesn't expect an error.
If you have an idea where to put the test case instead just let me know and I'll amend my PR.
=> Allow tag names without dashes

docs/api.md
Per the HTML spec you can put a scheme-relative url, e.g. `//google.com` as the src of an iframe: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-src
But Zoid sniffs the protocol in isSameDomain (from cross-domain-utils) so it expects http or https. If a protocol is not provided, the preload page spinner spins infinitely as in #202.
This makes it explicit that a protocol should be provided.
=> Update documentation to avoid scheme-relative URLs

docs/api.md
Found this typo in docs after copy/pasting the code on my files.
=> Fix typo in API docs

README.md
I found this video to assist with my implementation of Zoid and added it to the readme. I found it useful as the demos folder examples were a bit lacking.
=> Add video tutorial link

docs/api.md
`frame` element should be `node` element
=> Fixing typo in API docs

src/component/props.js
Validation errors were being blocked for edge case where user closes popup window quickly when `onClick`is implemented and causes iframe to show in window.  The debug flag was blocking error messages that are valuable for debugging this issue.
https://github.com/paypal/paypal-checkout-components/issues/1339
=> Maint: Debug is blocking validation

src/component/component.js
Added optional boolean to LoggerPayload. Without this, causes flow errors in paypal-checkout-components that relies on zoid flow type definitions.
Related beaver-logger commit: https://github.com/krakenjs/beaver-logger/commit/b63f28b6eafa306aabbdd5d4ba5e29691461d91f
=> Added optional boolean to LoggerPayload

docs/api.md, src/parent/parent.js
`url` and `bridgeUrl` are on the same domain, it would be nice for `bridgeUrl` to also accepts a function so that we can have different bridge URLs for different environments.
=> feat(bridge): allow bridgeUrl to be a function

.travis.yml
#328 
The Travis CI builds are failing, with the error being 
What was happening was that older versions of installed modules were being used. This solution to this problem is to remove the node_modules folder before travis CI starts installing dependencies.
* Update the `.travis.yml` file to remove `node_modules` folder before running tests
=> closes #328 - Update .travis.yml file to fix CI build failure issue

.eslintignore
#326 
The command that checks if files conform with`eslint` in the codebase checks the `test/eslintrc.js` file too. That file should go into the ignore folder or else this error occurs when someone runs the linter on their local machine:
* Add `test/eslintrc.js` file into the `.eslintignore` file
=> closes #326 - add test/eslintrc.js file to estlintignore

src/parent/props.js, test/tests/props.js
1. Bug fix for the issue from Honey integration where `commit` query param wasn't being passed down to SDK. 
2. Added tests and verified
=> Updating false value check for props

src/drivers/vue.js, test/tests/drivers.js
**Added support to handle kebab-case props in the Vue driver**
According Vue style guide best practices the props on template components should be passed in in kebab-case format.
_Vue docs reference_: https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended.
_Issue reference_: https://github.com/paypal/paypal-checkout-components/issues/1338#issuecomment-777005173
_Associated PR_: https://github.com/paypal/paypal-checkout-components/pull/1650
=> Vue driver support for kebab-case

demo/basic/popup/index.htm, demo/index.htm
While doing some reading of docs I noticed a couple non-functional demos. The popup demo is an easy fix, but I couldn't find a reference to the "script tag component" so just deleted that.
Not sure how to get this published to the krakenjs docs site, will need help with that.
=> Fixing broken demos for basic popup and missing script demo

src/drivers/vue.js, test/tests/drivers.js
**Reasoning**
In Vue the prop name `style` is reserved thus if the user wants to pass in a style for the PayPal button this won't work, instead the user now can pass in a `style-object` prop with the desire styling for the button.
To keep Zoid generic, we are passing in the original prop name, so if Zoid is used for other application the user will received the expected prop name in the component.
**Change**
Added logic on the Vue driver to replace the prop name `styleObject` or `style-object` by a `style` prop.
Reference: https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax-1
=> Vue driver logic for prop name replacement (style prop).

.github/workflows/node.js.yml, docs/api/prop-definitions.md, src/component/component.js, src/component/props.js, src/parent/parent.js, src/parent/props.js, src/types.js, test/tests/props.js
For context:
- https://github.com/krakenjs/zoid/pull/376
- https://github.com/krakenjs/zoid/pull/381
=> Support passing container to component prop helper functions

docs/api/prop-definitions.md, src/component/component.js, src/component/props.js, src/parent/parent.js, src/parent/props.js, src/types.js, test/tests/props.js
* Pass container to prop definitions when available (#378 
* Avoid re-decorating the same prop multiple times
For context:
- https://github.com/krakenjs/zoid/pull/376
- https://github.com/krakenjs/zoid/pull/381
=> Support passing container to component prop helper functions (#382)

docs/api/instance.md, src/component/props.js, src/constants.js, src/parent/parent.js, test/tests/error.js, test/tests/happy.jsx
Added event triggers for prerender steps.
Feature required on [#402](https://github.com/krakenjs/zoid/issues/402)
=> feat: added events on prerender start and finish

src/constants.js, src/parent/parent.js, test/tests/error.js, test/tests/remove.jsx
We have identified a few errors that zoid throws that cannot be caught by the implementation code (`render.catch() `and `close.catch()`) during asynchronous dismounts. Although this can occur in every webpage, it's primarily an issue when using React as seen here: [Issue #334](https://github.com/krakenjs/zoid/issues/334)
With this change, we first check if the container element has been removed from the DOM or the user has navigated away from the page mid-render. In these scenarios we should avoid throwing errors.
Here are 3 examples:
https://github.com/krakenjs/zoid/blob/main/src/parent/parent.js#L857
https://github.com/krakenjs/zoid/blob/main/src/parent/parent.js#L826
https://github.com/krakenjs/zoid/blob/main/src/parent/parent.js#L1172
These 3 error flows eventually cause the promise …
=> fix: avoid throwing errors if container is no longer in page

src/child/child.js
We currently throw an error when the Zoid version doesn't strictly match. This change will only check for major version upgrades before throwing an error, patches and minor changes will be allowed to be different.
=> fix: only throwing errors for major version changes

src/parent/parent.js
Rolling back the additional checks put in place to reduce the frequency of `Detected iframe close` error.
=> revert: rollback additional iframe checks

.github/workflows/publish.yml, index.js
* used `node v12.13` in `publish` gha due to compatibility issue with `npm v3`, which is pinned by `grumbler-scripts`.
* added `eslint disable` to `index.js` due to an issue where `eslint` interprets `.frame` as a file extension after dist has been deleted.
=> chore: more ci fixes

src/child/props.js, src/component/props.js, src/parent/parent.js, test/tests/domain.js, test/tests/props.js
Allows trusted domains to be specified for passing props to children with different domain.
https://paypal.atlassian.net/browse/DTCHKINT-1568
=> feat(venmo): allow trusted domains

src/child/child.js, src/lib/window.js, src/parent/parent.js
Window name wasn't being updated if redirecting in popup. This caused blank windows to open when sending focus event to popup as window name did not match.
Send updated name to parent initialization to update the proxy window name.
=> fix(venmo): window name

src/parent/parent.js
We're seeing rare cases when we see `Detected iframe close` before second render has a chance to finish in slow browsers with poor connection. With this change, we're adding an additional check before we decide to throw the error. 
Here is the example:
https://github.com/krakenjs/zoid/blob/main/src/parent/parent.js#L866
=> fix: reduce frequency of iframe removed error

src/parent/parent.js
Ensure `setName` is called with `name` present and in the context of a popup.
=> fix(initChild): setName is applied in popup context

src/drivers/script.js
`DOMNodeInserted` and a handful of other events will become unsupported in chrome [later this year](https://developer.chrome.com/blog/mutation-events-deprecation/).
=> Remove listener for deprecated DOMNodeInserted event

test/tests/dimensions.jsx
* This test case is consistently failing. 
* I also notice with manual testing that `innerHeight` is not set same as the dimensions property passed to Zoid.
* Skipping this test case until we can find the root cause of this issue.
```
✗ should render a component to a popup with specific px dimensions
Error: Expected height to be 253, got 200
```
* Tested with a dummy PR as well: https://github.com/krakenjs/zoid/pull/465
=> fix: skip failing test

src/child/child.js, src/component/component.js, src/component/validate.js, src/parent/parent.js, test/tests/extensions.jsx, test/tests/index.js
* We have a use case where its necessary to add support for additional methods on the Zoid component instance. 
* To support this use case  `getExtensions` callback is being added to create method.
* Zoid would call this method to add the additional properties returned by this callback on the component instances. 
* This method will accept the parent props as an argument so that the extended methods could interact with props passed during initialization. 
* The implementation will ensure that `getExtensions` cannot override any of the existing methods in Zoid like render, clone etc. 
Sample usage
```javascript
const MyComponent = zoid.create({
tag: "custom-buttons",
getExtensions: (parent) => {
// methods defined in parent props, like `onCancel` will be available in 
// props returned by …
```
=> feat: support additional properties to be added to zoid component from the client

src/child/child.js, src/component/component.js, src/component/validate.js, src/parent/parent.js, test/tests/extensions.jsx, test/tests/index.js
* We have a use case where its necessary to add support for additional methods on the Zoid component instance. 
* To support this use case  `getExtensions` callback is being added to create method.
* Zoid would call this method to add the additional properties returned by this callback on the component instances. 
* This method will accept the parent props as an argument so that the extended methods could interact with props passed during initialization. 
* The implementation will ensure that `getExtensions` cannot override any of the existing methods in Zoid like render, clone etc. 
Sample usage
```javascript
const MyComponent = zoid.create({
tag: "custom-buttons",
getExtensions: (parent) => {
// methods defined in parent props, like `onCancel` will be available in 
// props returned by …
```
=> feat: add getExtensions method to extend zoid component instance
